name: Outpost
version: 1.0.0
main: land.face.outpost.OutpostPlugin
author: Faceguy
description: Make sum outposts
depend:
  - Facecore
  - Strife
  - PoggersGuilds
softdepend:
  - Waypointer
  - PlaceholderAPI
api-version: 1.18

commands:
  outpost:
    usage: /<command>
    aliases: [outposts]
    description: outpostsz